---
title: Arte de Pixel
description: Crea un editor de arte pixelado.
hero_image: images/pixel-art.png
theme: azul marino
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: arte
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Crear una cuadrícula de píxeles
  - 
    title: 'Desafío: Modifica el tamaño de la cuadrícula'
  - 
    title: 'Colorea los píxeles'
  - 
    title: 'Desafío: Haz que todos los píxeles sean clicablese'
  - 
    title: 'Añade una paleta de colores'
  - 
    title: 'Desafío: Añade más colores a la paleta'
  - 
    title: 'Desafío: agregar más colores a la paleta'
