---
title: Pixel art
description: Create a pixel art editor using HTML, CSS, and JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: arte
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Robot parlanchín
  - 
    title: Lo que necesitarás
  - 
    title: Create a grid of pixels
  - 
    title: 'Challenge: resize your grid'
  - 
    title: Colour the pixels
  - 
    title: 'Challenge: make all pixels clickable'
  - 
    title: Add a colour palette
  - 
    title: 'Challenge: add more colours to the palette'
