---
title: Pixel art
description: Créer un éditeur de pixel art.
hero_image: images/pixel-art.png
theme: bleu marin
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmation-1, phys-comp-0, fabrication-0, communauté-0
original_url: https://codeclubprojects.org/fr-FR/webdev/pixel-art/
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Créer une grille de pixels
  - 
    title: 'Défi : Redimensionner votre grille'
  - 
    title: 'Colorer les pixels'
  - 
    title: 'Défi : Rendre tous les pixels cliquable'
  - 
    title: 'Ajouter une palette de couleur'
  - 
    title: 'Défi : Ajouter plus de couleurs à la palette'
  - 
    title: 'Challenge: add more colours to the palette'
