---
title: Pixel art
description: Crea un editor di Pixel Art.
hero_image: images/pixel-art.png
theme: blu marino
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Creazione di una griglia di pixel
  - 
    title: 'Sfida: Ridimensiona la griglia'
  - 
    title: Colora i pixel
  - 
    title: 'Sfida: Rendi tutti i pixel selezionabili'
  - 
    title: Aggiungi una tavolozza di colori
  - 
    title: 'Sfida: Aggiungi più colori alla tavolozza'
  - 
    title: 'Challenge: aggiungi più colori alla tavolozza'
